language: node_js
node_js:
- '6.1'
- '6.0'
- '6'
- node
services:
- mongodb
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm start | npm test
env:
  matrix:
  - secure: X/265DM7HtCM7gWRD2M6AJ4Vc1Zz1RRZ2TVGnhz6FESkLE49loIbNY2kRt+fiw6oKXpo40RCVOO30AzMRXiWSXVuYUGkGmAYOLM2sCE48Bo+fng9K08wHv/gHM4FxSRu7uQikdllh5innXHyBY8gnRN/peV/goUkDEzx3CsP2o6mZvk6HMC58YrezodXN8NpCblyl4NZE6R2zQ4Zh3eM3w6nA0mVH1dEg5TVdbfB6tL+zXzp4ETVGNKQSloz2Cy9ruqONby2cW2uQFBGjvozoeZKbE/g2nmIqMoNunasfW7RBkz7noUfEa5WC1moBqXOfxw1wDqiPNwQmucEQ0OuoxxVjzqUk6MzGpLc33To8QVMRi5Bnx+OwkKJXyqHE30Ynvm9pA0SqGqH8QGH9l3PZJvUaZBdhCbFejyASFdIF/ppx4qkfpoRiNzg/EAdPcXRnrfnVBDnR0MLeOq7wvYLMS8wZ/9XPf2dTpXo7d9hMR8+h/pUrVU+mevOOVyTkjdMS7w5eOUMjJIj3YEl2Wswfhd1I5n9s5qUg7e37krZFo6YIblptGrRh/GlikZxIy1RMFmWH0oqr9olwjtfE4ITZhfFsKVGEfxxjWuhd+VIBrzDlN9wboCmD3tKHZUbEx9DMWMDgq5uViwyyEKFVCkG82rI+ybY9785OnRRiuVYOtA=
  - secure: IhNEApu+LLu96CaBJEcug6+9UfzSfPyFwzsQJYl9OIYW7XJkvKDh+s1c0pOzhqitfbl3n3EdJmQ1nuE+wwtZMkDNndmFvNjqJdX2v2qAp6w4rDW2B/G9C3OknvK4nnmE3MuGbDIvuJo3Ox3XRDOnK+ypt+hnxDLT7XNKsziIUd8IyzBTqDprdh3hOdwJKHVKlgHoITkobRd3ov57R6posmuSsaUf6g8O2t0NhPQqf6bXv6RUassUINQDFnSmnt0dwcn2ineCFa/UPgXolcDeP6+j8f+OBvTT/w4YZPJPQpBjQjcIPl9HmzOMnyh19lFm1qsUZN5vhc1lCe4vYgwDmnjFSktZMiu+gYJ5I6xc8K2xQ6eHDF++2ALmBQM9XyBvwmJlTjlBP0/aWxgZh3Nqw1RlVqYmh3gwpf9HGPyZnZ/DDH2oOM6b785OJ2bqml+pPTSYNyVbk5dbDlfk2g+h139I0F3zpbj6plRXMIgfQeUaGnmBBoaVZK4NmBXqU2Fo0SHlibUoPG6Fvmhc91Ryyqtaof4H+2QD7ivA7qJb/kzN2OwnljTKGKv2X2jgeT3odIXF1NxKv29jTVoco32d0sZejl6Ie/LHnLJ5e/9QfNcIKm5fQ06oyT0PeuKtlSG+8VDyQw47xhgZx5xT0cJ5tSo6GU5ALqzAeSVffma0C4c=
  - secure: nHToBB6qOTm8aWLn3Cxmx3ZYRiB5k+m/ZfwMNS+KtRWxKCY9RZHlUGYQZoCr563OzRMH+zQ2eSNJch4/tezr/nDtiDRuq3NguF66WQn1gLaTXMNsPCs0nML6H88dI0jHZMCUofviBcBuNjBNudyuUJIKOdqnAw8BEGk17EAciHLqFbxmuUmKI2mc8UEgL92eU9riCXJAWj8gxJEZBDebxRh3tO1bFrZiDV+S2VSZN89rFv+jSwun1EtPEQEDyEBJAXkb4Y6ZQQ529YYZLrDzMkDSXDVKea1LmJrkjoP89S3JimJxjvb3ffjAi3faKLkD7olGmdoNCMD5sGWI6I14yk9uZ+kPLTcAMyFTtdzkfBlb/bBK1KPrp+UrEi4eMS9a2DEwzH0Msb0eMTf+rONch8YVEiAAEocSVpWjVIREItP/Exf3wmWAS8y2aohN1x8zBVagFCyBTVEeXvcSW6AzXIxybGfih4P4TGoiaZ3JqqWuQ+zqtanFwAR9c+PybW8u3pzh8FwhpQN6DMG8onYBeurdhQbpQGZ3Xgf1jVR+6u7kB7ENp8pqa0Zh1k8zYKK8rOagESqm8lDPvL+UeWlqwVMzQurETu31CwVOvCQXt4Zy7TUH2kFjY0rLrlHc463g/IeDR5U+yZ+e4N6sy7zAvbXrLOOGfCRl7kSfQEK8A1o=
