language: node_js
node_js:
- '6.1'
- '6.0'
- '6'
- node
services:
- mongodb
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm start
- npm test
